In [36]:
import pandas as pd

In [37]:
df_med = pd.read_csv("dados/trusted/medical_appointment_no_show.csv")

In [38]:
df_clima = pd.read_csv('dados/trusted/clima.csv')

In [39]:

def criar_coluna_estacao(df, coluna_data):
    
    def _definir_estacao_logica(data):
        if pd.isna(data):
            return pd.NA
            
        mes = data.month
        dia = data.day
        
        if (mes == 12 and dia >= 21) or (mes in [1, 2]) or (mes == 3 and dia < 21):
            return "VERAO"
        elif (mes == 3 and dia >= 21) or (mes in [4, 5]) or (mes == 6 and dia < 21):
            return "OUTONO"
        elif (mes == 6 and dia >= 21) or (mes in [7, 8]) or (mes == 9 and dia < 22):
            return "INVERNO"
        elif (mes == 9 and dia >= 22) or (mes in [10, 11]) or (mes == 12 and dia < 21):
            return "PRIMAVERA"
        else:
            return pd.NA
    coluna_dt = pd.to_datetime(df[coluna_data], format='%d/%m/%Y', errors='coerce')
    
    df['Estacao_Ano'] = coluna_dt.apply(_definir_estacao_logica)
    
    return df

In [40]:
df_clima = criar_coluna_estacao(df_clima, 'DATA')

In [41]:
df_med

,UNNAMED: 0,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,DIABETES,ALCOHOLISM,HANDCAP,SMS_RECEIVED,NO-SHOW
0,0,2.987250e+13,5642903,F,29/04/2016 18:38:08,29/04/2016 00:00:00,62,JARDIM DA PENHA,0,1,0,0,0,1,0
1,1,5.589978e+14,5642503,M,29/04/2016 16:08:27,29/04/2016 00:00:00,56,JARDIM DA PENHA,0,0,0,0,0,1,0
2,2,4.262962e+12,5642549,F,29/04/2016 16:19:04,29/04/2016 00:00:00,62,MATA DA PRAIA,0,0,0,0,0,1,0
3,3,8.679512e+11,5642828,F,29/04/2016 17:29:31,29/04/2016 00:00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,1,0
4,4,8.841186e+12,5642494,F,29/04/2016 16:07:23,29/04/2016 00:00:00,56,JARDIM DA PENHA,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110521,110522,2.572134e+12,5651768,F,03/05/2016 09:15:35,07/06/2016 00:00:00,56,MARIA ORTIZ,0,0,0,0,0,0,0
110522,110523,3.596266e+12,5650093,F,03/05/2016 07:27:33,07/06/2016 00:00:00,51,MARIA ORTIZ,0,0,0,0,0,0,0
110523,110524,1.557663e+13,5630692,F,27/04/2016 16:03:52,07/06/2016 00:00:00,21,MARIA ORTIZ,0,0,0,0,0,0,0
110524,110525,9.213493e+13,5630323,F,27/04/2016 15:09:23,07/06/2016 00:00:00,38,MARIA ORTIZ,0,0,0,0,0,0,0
110525,110526,3.775115e+14,5629448,F,27/04/2016 13:30:56,07/06/2016 00:00:00,54,MARIA ORTIZ,0,0,0,0,0,0,0

In [42]:
df_clima

,DATA,HORA_UTC,PRECIPITACAO_MM,PRESSAO_ESTACAO_MB,PRESSAO_MAX_MB,PRESSAO_MIN_MB,RADIACAO_KJ_M2,TEMP_AR_C,TEMP_ORVALHO_C,TEMP_MAX_C,TEMP_MIN_C,TEMP_ORVALHO_MAX_C,TEMP_ORVALHO_MIN_C,UMIDADE_MAX,UMIDADE_MIN,UMIDADE_RELATIVA,VENTO_DIRECAO_GRAUS,VENTO_RAJADA_MAX_MS,VENTO_VELOCIDADE_MS,Estacao_Ano
0,01/01/2016,00:00,0.0,924.1,924.1,923.6,-9999.0,23.8,19.1,25.1,23.8,19.2,18.8,75,69,75,322,7.0,3.4,VERAO
1,01/01/2016,01:00,0.0,924.4,924.5,924.1,-9999.0,23.0,18.7,23.8,23.0,19.2,18.7,77,75,77,325,7.0,3.7,VERAO
2,01/01/2016,02:00,0.0,924.1,924.6,924.1,-9999.0,22.5,18.4,23.1,22.4,18.8,18.4,78,76,77,334,7.8,3.3,VERAO
3,01/01/2016,03:00,0.0,923.9,924.1,923.8,-9999.0,22.2,18.2,22.5,22.0,18.4,18.1,79,77,78,306,7.3,2.2,VERAO
4,01/01/2016,04:00,0.0,923.3,924.0,923.3,-9999.0,21.7,18.0,22.2,21.7,18.2,18.0,79,78,79,322,7.7,4.2,VERAO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,31/12/2016,19:00,0.0,923.3,924.2,923.0,442.2,26.3,16.7,26.3,25.3,18.0,16.5,63,56,56,307,6.6,1.7,VERAO
8780,31/12/2016,20:00,0.0,923.4,923.5,923.1,544.8,27.7,16.1,27.7,26.3,16.5,14.6,55,46,49,353,5.1,1.6,VERAO
8781,31/12/2016,21:00,0.0,923.6,924.0,923.4,195.4,27.1,16.4,27.7,27.0,16.5,15.9,53,49,52,43,4.5,0.7,VERAO
8782,31/12/2016,22:00,0.0,924.1,924.3,923.6,29.3,26.6,16.8,27.2,26.6,16.8,16.2,55,51,55,331,3.4,1.1,VERAO
8783,31/12/2016,23:00,0.0,925.0,925.0,924.0,-9999.0,26.0,17.6,26.7,26.0,17.6,16.8,60,55,60,337,4.2,1.5,VERAO

In [43]:
def criar_coluna_classificacao_temp(df, coluna_temp):
    """
    Recebe um DataFrame e o nome da coluna de temperatura,
    e cria uma nova coluna 'Classificacao_Temp' com a classificação.
    """
    
    def _classificar_temp_logica(temp):
        """
        Lógica interna para classificar a temperatura.
        """
        # Trata valores nulos ou não numéricos
        if pd.isna(temp) or not isinstance(temp, (int, float)):
            return pd.NA
        
        # Lógica de classificação
        if temp < 10:
            return "MUITO_FRIO"
        elif 10 <= temp < 17:
            return "FRIO"
        elif 17 <= temp < 24:
            return "AGRADAVEL"
        elif 24 <= temp < 30:
            return "QUENTE"
        elif temp >= 30:
            return "MUITO_QUENTE"
        # O 'else' aqui só pega casos que não deveriam ocorrer com números válidos
        else:
            return pd.NA

    # Cria a nova coluna aplicando a lógica à coluna de temperatura
    df['Classificacao_Temp'] = df[coluna_temp].apply(_classificar_temp_logica)
    
    return df

In [44]:
df_clima = criar_coluna_classificacao_temp(df_clima, 'TEMP_AR_C')

In [45]:
df_clima

,DATA,HORA_UTC,PRECIPITACAO_MM,PRESSAO_ESTACAO_MB,PRESSAO_MAX_MB,PRESSAO_MIN_MB,RADIACAO_KJ_M2,TEMP_AR_C,TEMP_ORVALHO_C,TEMP_MAX_C,...,TEMP_ORVALHO_MAX_C,TEMP_ORVALHO_MIN_C,UMIDADE_MAX,UMIDADE_MIN,UMIDADE_RELATIVA,VENTO_DIRECAO_GRAUS,VENTO_RAJADA_MAX_MS,VENTO_VELOCIDADE_MS,Estacao_Ano,Classificacao_Temp
0,01/01/2016,00:00,0.0,924.1,924.1,923.6,-9999.0,23.8,19.1,25.1,...,19.2,18.8,75,69,75,322,7.0,3.4,VERAO,AGRADAVEL
1,01/01/2016,01:00,0.0,924.4,924.5,924.1,-9999.0,23.0,18.7,23.8,...,19.2,18.7,77,75,77,325,7.0,3.7,VERAO,AGRADAVEL
2,01/01/2016,02:00,0.0,924.1,924.6,924.1,-9999.0,22.5,18.4,23.1,...,18.8,18.4,78,76,77,334,7.8,3.3,VERAO,AGRADAVEL
3,01/01/2016,03:00,0.0,923.9,924.1,923.8,-9999.0,22.2,18.2,22.5,...,18.4,18.1,79,77,78,306,7.3,2.2,VERAO,AGRADAVEL
4,01/01/2016,04:00,0.0,923.3,924.0,923.3,-9999.0,21.7,18.0,22.2,...,18.2,18.0,79,78,79,322,7.7,4.2,VERAO,AGRADAVEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,31/12/2016,19:00,0.0,923.3,924.2,923.0,442.2,26.3,16.7,26.3,...,18.0,16.5,63,56,56,307,6.6,1.7,VERAO,QUENTE
8780,31/12/2016,20:00,0.0,923.4,923.5,923.1,544.8,27.7,16.1,27.7,...,16.5,14.6,55,46,49,353,5.1,1.6,VERAO,QUENTE
8781,31/12/2016,21:00,0.0,923.6,924.0,923.4,195.4,27.1,16.4,27.7,...,16.5,15.9,53,49,52,43,4.5,0.7,VERAO,QUENTE
8782,31/12/2016,22:00,0.0,924.1,924.3,923.6,29.3,26.6,16.8,27.2,...,16.8,16.2,55,51,55,331,3.4,1.1,VERAO,QUENTE
8783,31/12/2016,23:00,0.0,925.0,925.0,924.0,-9999.0,26.0,17.6,26.7,...,17.6,16.8,60,55,60,337,4.2,1.5,VERAO,QUENTE

In [46]:
df_med

,UNNAMED: 0,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,DIABETES,ALCOHOLISM,HANDCAP,SMS_RECEIVED,NO-SHOW
0,0,2.987250e+13,5642903,F,29/04/2016 18:38:08,29/04/2016 00:00:00,62,JARDIM DA PENHA,0,1,0,0,0,1,0
1,1,5.589978e+14,5642503,M,29/04/2016 16:08:27,29/04/2016 00:00:00,56,JARDIM DA PENHA,0,0,0,0,0,1,0
2,2,4.262962e+12,5642549,F,29/04/2016 16:19:04,29/04/2016 00:00:00,62,MATA DA PRAIA,0,0,0,0,0,1,0
3,3,8.679512e+11,5642828,F,29/04/2016 17:29:31,29/04/2016 00:00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,1,0
4,4,8.841186e+12,5642494,F,29/04/2016 16:07:23,29/04/2016 00:00:00,56,JARDIM DA PENHA,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110521,110522,2.572134e+12,5651768,F,03/05/2016 09:15:35,07/06/2016 00:00:00,56,MARIA ORTIZ,0,0,0,0,0,0,0
110522,110523,3.596266e+12,5650093,F,03/05/2016 07:27:33,07/06/2016 00:00:00,51,MARIA ORTIZ,0,0,0,0,0,0,0
110523,110524,1.557663e+13,5630692,F,27/04/2016 16:03:52,07/06/2016 00:00:00,21,MARIA ORTIZ,0,0,0,0,0,0,0
110524,110525,9.213493e+13,5630323,F,27/04/2016 15:09:23,07/06/2016 00:00:00,38,MARIA ORTIZ,0,0,0,0,0,0,0
110525,110526,3.775115e+14,5629448,F,27/04/2016 13:30:56,07/06/2016 00:00:00,54,MARIA ORTIZ,0,0,0,0,0,0,0

In [47]:

def preparar_df_clima(df_clima):
    """
    Processa o DataFrame de clima, tratando decimais e criando a CHAVE_HORA.
    """
    print("Processando df_clima...")
    coluna_limpa = df_clima['TEMP_AR_C'].astype(str).str.replace(',', '.', regex=False)
    df_clima['TEMP_AR_C'] = pd.to_numeric(coluna_limpa, errors='coerce')
    
    df_clima['DATA_HORA_CLIMA'] = df_clima['DATA'] + ' ' + df_clima['HORA_UTC']
    df_clima['DATA_HORA_CLIMA'] = pd.to_datetime(df_clima['DATA_HORA_CLIMA'], format='%d/%m/%Y %H:%M', errors='coerce')
    
    df_clima['CHAVE_HORA'] = df_clima['DATA_HORA_CLIMA']
    
    return df_clima.drop(columns=['DATA', 'HORA_UTC'])

def preparar_df_med(df_med, coluna_base):
    """
    Processa o DataFrame de consultas, triturando a coluna de tempo para a hora.
    """
    print(f"Processando df_med usando {coluna_base}...")
    df_med[coluna_base] = pd.to_datetime(df_med[coluna_base], format='%d/%m/%Y %H:%M:%S', errors='coerce')

    df_med['CHAVE_HORA'] = df_med[coluna_base].dt.floor('H')
    
    return df_med

In [48]:

df_clima_processado = preparar_df_clima(df_clima.copy())

df_med_processado = preparar_df_med(df_med.copy(), 'SCHEDULEDDAY')

print("\nRealizando o merge...")

df_final = pd.merge(
    df_med_processado, 
    df_clima_processado, 
    on='CHAVE_HORA', 
    how='left'
)

print("\nMerge concluído!")
print(f"Total de linhas no DataFrame final: {len(df_final)}")
print("\nVisualização das primeiras linhas (colunas chave):")
print(df_final[['SCHEDULEDDAY', 'CHAVE_HORA', 'TEMP_AR_C', 'UMIDADE_RELATIVA']].head())

Processando df_clima...
Processando df_med usando SCHEDULEDDAY...

Realizando o merge...

Merge concluído!
Total de linhas no DataFrame final: 110526

Visualização das primeiras linhas (colunas chave):
         SCHEDULEDDAY          CHAVE_HORA  TEMP_AR_C  UMIDADE_RELATIVA
0 2016-04-29 18:38:08 2016-04-29 18:00:00       15.2              77.0
1 2016-04-29 16:08:27 2016-04-29 16:00:00       16.3              72.0
2 2016-04-29 16:19:04 2016-04-29 16:00:00       16.3              72.0
3 2016-04-29 17:29:31 2016-04-29 17:00:00       16.4              72.0
4 2016-04-29 16:07:23 2016-04-29 16:00:00       16.3              72.0

C:\Users\ivanm\AppData\Local\Temp\ipykernel_4748\1926484615.py:23: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_med['CHAVE_HORA'] = df_med[coluna_base].dt.floor('H')

In [49]:
df_final

,UNNAMED: 0,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,...,TEMP_ORVALHO_MIN_C,UMIDADE_MAX,UMIDADE_MIN,UMIDADE_RELATIVA,VENTO_DIRECAO_GRAUS,VENTO_RAJADA_MAX_MS,VENTO_VELOCIDADE_MS,Estacao_Ano,Classificacao_Temp,DATA_HORA_CLIMA
0,0,2.987250e+13,5642903,F,2016-04-29 18:38:08,29/04/2016 00:00:00,62,JARDIM DA PENHA,0,1,...,10.9,77.0,71.0,77.0,137.0,5.3,2.2,OUTONO,FRIO,2016-04-29 18:00:00
1,1,5.589978e+14,5642503,M,2016-04-29 16:08:27,29/04/2016 00:00:00,56,JARDIM DA PENHA,0,0,...,10.8,73.0,71.0,72.0,120.0,4.0,1.4,OUTONO,FRIO,2016-04-29 16:00:00
2,2,4.262962e+12,5642549,F,2016-04-29 16:19:04,29/04/2016 00:00:00,62,MATA DA PRAIA,0,0,...,10.8,73.0,71.0,72.0,120.0,4.0,1.4,OUTONO,FRIO,2016-04-29 16:00:00
3,3,8.679512e+11,5642828,F,2016-04-29 17:29:31,29/04/2016 00:00:00,8,PONTAL DE CAMBURI,0,0,...,10.9,72.0,71.0,72.0,120.0,3.5,1.1,OUTONO,FRIO,2016-04-29 17:00:00
4,4,8.841186e+12,5642494,F,2016-04-29 16:07:23,29/04/2016 00:00:00,56,JARDIM DA PENHA,0,1,...,10.8,73.0,71.0,72.0,120.0,4.0,1.4,OUTONO,FRIO,2016-04-29 16:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110521,110522,2.572134e+12,5651768,F,2016-05-03 09:15:35,07/06/2016 00:00:00,56,MARIA ORTIZ,0,0,...,10.5,83.0,82.0,82.0,69.0,4.6,2.2,OUTONO,FRIO,2016-05-03 09:00:00
110522,110523,3.596266e+12,5650093,F,2016-05-03 07:27:33,07/06/2016 00:00:00,51,MARIA ORTIZ,0,0,...,11.3,85.0,83.0,83.0,59.0,4.7,2.1,OUTONO,FRIO,2016-05-03 07:00:00
110523,110524,1.557663e+13,5630692,F,2016-04-27 16:03:52,07/06/2016 00:00:00,21,MARIA ORTIZ,0,0,...,12.8,75.0,72.0,74.0,342.0,7.7,3.4,OUTONO,AGRADAVEL,2016-04-27 16:00:00
110524,110525,9.213493e+13,5630323,F,2016-04-27 15:09:23,07/06/2016 00:00:00,38,MARIA ORTIZ,0,0,...,12.9,77.0,72.0,72.0,308.0,5.6,2.8,OUTONO,AGRADAVEL,2016-04-27 15:00:00
110525,110526,3.775115e+14,5629448,F,2016-04-27 13:30:56,07/06/2016 00:00:00,54,MARIA ORTIZ,0,0,...,13.9,86.0,81.0,86.0,301.0,6.8,3.5,OUTONO,FRIO,2016-04-27 13:00:00

tirar colunas: ALCOHOLISM PRESSAO_ESTACAO_MB PRESSAO_MAX_MB PRESSAO_MIN_MB RADIACAO_KJ_M2 TEMP_ORVALHO_C TEMP_ORVALHO_MAX_C TEMP_ORVALHO_MIN_C UMIDADE_MAX UMIDADE_MIN VENTO_DIRECAO_GRAUS VENTO_RAJADA_MAX_MS VENTO_VELOCIDADE_MS

In [50]:
colunas_para_dropar = [
    'ALCOHOLISM',
    'PRESSAO_ESTACAO_MB',
    'PRESSAO_MAX_MB',
    'PRESSAO_MIN_MB',
    'RADIACAO_KJ_M2',
    'TEMP_ORVALHO_C',
    'TEMP_ORVALHO_MAX_C',
    'TEMP_ORVALHO_MIN_C',
    'UMIDADE_MAX',
    'UMIDADE_MIN',
    'VENTO_DIRECAO_GRAUS',
    'VENTO_RAJADA_MAX_MS',
    'VENTO_VELOCIDADE_MS'
]

df_final.drop(colunas_para_dropar, axis=1, inplace=True)

In [51]:
df_final

,UNNAMED: 0,PATIENTID,APPOINTMENTID,GENDER,SCHEDULEDDAY,APPOINTMENTDAY,AGE,NEIGHBOURHOOD,SCHOLARSHIP,HIPERTENSION,...,NO-SHOW,CHAVE_HORA,PRECIPITACAO_MM,TEMP_AR_C,TEMP_MAX_C,TEMP_MIN_C,UMIDADE_RELATIVA,Estacao_Ano,Classificacao_Temp,DATA_HORA_CLIMA
0,0,2.987250e+13,5642903,F,2016-04-29 18:38:08,29/04/2016 00:00:00,62,JARDIM DA PENHA,0,1,...,0,2016-04-29 18:00:00,0.0,15.2,16.5,15.2,77.0,OUTONO,FRIO,2016-04-29 18:00:00
1,1,5.589978e+14,5642503,M,2016-04-29 16:08:27,29/04/2016 00:00:00,56,JARDIM DA PENHA,0,0,...,0,2016-04-29 16:00:00,0.0,16.3,16.3,15.8,72.0,OUTONO,FRIO,2016-04-29 16:00:00
2,2,4.262962e+12,5642549,F,2016-04-29 16:19:04,29/04/2016 00:00:00,62,MATA DA PRAIA,0,0,...,0,2016-04-29 16:00:00,0.0,16.3,16.3,15.8,72.0,OUTONO,FRIO,2016-04-29 16:00:00
3,3,8.679512e+11,5642828,F,2016-04-29 17:29:31,29/04/2016 00:00:00,8,PONTAL DE CAMBURI,0,0,...,0,2016-04-29 17:00:00,0.0,16.4,16.4,16.1,72.0,OUTONO,FRIO,2016-04-29 17:00:00
4,4,8.841186e+12,5642494,F,2016-04-29 16:07:23,29/04/2016 00:00:00,56,JARDIM DA PENHA,0,1,...,0,2016-04-29 16:00:00,0.0,16.3,16.3,15.8,72.0,OUTONO,FRIO,2016-04-29 16:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110521,110522,2.572134e+12,5651768,F,2016-05-03 09:15:35,07/06/2016 00:00:00,56,MARIA ORTIZ,0,0,...,0,2016-05-03 09:00:00,0.0,13.5,13.9,13.5,82.0,OUTONO,FRIO,2016-05-03 09:00:00
110522,110523,3.596266e+12,5650093,F,2016-05-03 07:27:33,07/06/2016 00:00:00,51,MARIA ORTIZ,0,0,...,0,2016-05-03 07:00:00,0.0,14.2,14.4,14.1,83.0,OUTONO,FRIO,2016-05-03 07:00:00
110523,110524,1.557663e+13,5630692,F,2016-04-27 16:03:52,07/06/2016 00:00:00,21,MARIA ORTIZ,0,0,...,0,2016-04-27 16:00:00,0.0,17.9,18.5,17.9,74.0,OUTONO,AGRADAVEL,2016-04-27 16:00:00
110524,110525,9.213493e+13,5630323,F,2016-04-27 15:09:23,07/06/2016 00:00:00,38,MARIA ORTIZ,0,0,...,0,2016-04-27 15:00:00,0.0,18.1,18.1,17.4,72.0,OUTONO,AGRADAVEL,2016-04-27 15:00:00
110525,110526,3.775115e+14,5629448,F,2016-04-27 13:30:56,07/06/2016 00:00:00,54,MARIA ORTIZ,0,0,...,0,2016-04-27 13:00:00,0.2,16.5,17.3,16.5,86.0,OUTONO,FRIO,2016-04-27 13:00:00

In [ ]:
df_final.to_csv('dados/refined/cancelamentos_com_clima.csv', index=False)